-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_o8_fund_transaction`;
DROP TABLE IF EXISTS `civicrm_o8_fund_component`;
DROP TABLE IF EXISTS `civicrm_o8_fund_category`;
DROP TABLE IF EXISTS `civicrm_o8_fund_account`;
DROP TABLE IF EXISTS `civicrm_o8_fund`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_o8_fund
-- *
-- * Fund
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_fund` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Fund ID',
  `code` varchar(255) NOT NULL COMMENT 'Fund Code',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `name` varchar(255) NOT NULL COMMENT 'Fund Name',
  `target_cases` varchar(1255) COMMENT 'Target Cases.',
  `start_date` datetime NOT NULL COMMENT 'Fund Start Date',
  `end_date` datetime NOT NULL COMMENT 'Fund End Date',
  `amount` decimal(20,2) NOT NULL COMMENT 'Amount of the fund.',
  `description` text COMMENT 'Optional verbose description of the fund.',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the fund was created',
  `created_by` int unsigned COMMENT 'FK to Created Contact',
  `modified_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the fund was modified',
  `modified_by` int unsigned COMMENT 'FK to Modified Contact',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_code`(code),
  INDEX `index_name`(code),
  CONSTRAINT FK_civicrm_o8_fund_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE RESTRICT,
  CONSTRAINT FK_civicrm_o8_fund_created_by FOREIGN KEY (`created_by`) REFERENCES `civicrm_contact`(`id`) ON DELETE RESTRICT,
  CONSTRAINT FK_civicrm_o8_fund_modified_by FOREIGN KEY (`modified_by`) REFERENCES `civicrm_contact`(`id`) ON DELETE RESTRICT
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_o8_fund_account
-- *
-- * Account
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_fund_account` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique FundAccount ID',
  `code` varchar(255) NOT NULL COMMENT 'Account Code',
  `name` varchar(255) NOT NULL COMMENT 'Account Name',
  `description` text COMMENT 'Optional verbose description of the account.',
  `fund_id` int unsigned NOT NULL COMMENT 'FK to civicrm_o8_fund',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the account was created',
  `created_by` int unsigned COMMENT 'FK to Created Contact',
  `modified_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the account was modified',
  `modified_by` int unsigned COMMENT 'FK to Modified Contact',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_code`(code),
  INDEX `index_name`(code),
  CONSTRAINT FK_civicrm_o8_fund_account_fund_id FOREIGN KEY (`fund_id`) REFERENCES `civicrm_o8_fund`(`id`),
  CONSTRAINT FK_civicrm_o8_fund_account_created_by FOREIGN KEY (`created_by`) REFERENCES `civicrm_contact`(`id`) ON DELETE RESTRICT,
  CONSTRAINT FK_civicrm_o8_fund_account_modified_by FOREIGN KEY (`modified_by`) REFERENCES `civicrm_contact`(`id`) ON DELETE RESTRICT
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_o8_fund_category
-- *
-- * Fund Category
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_fund_category` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Fund Category ID',
  `code` varchar(255) NOT NULL COMMENT 'Category Code',
  `name` varchar(255) NOT NULL COMMENT 'Category Name',
  `description` text COMMENT 'Optional verbose description of the category.',
  `fund_id` int unsigned NOT NULL COMMENT 'FK to civicrm_o8_fund',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the category was created',
  `created_by` int unsigned COMMENT 'FK to Created Contact',
  `modified_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the category was modified',
  `modified_by` int unsigned COMMENT 'FK to Modified Contact',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_code`(code),
  INDEX `index_name`(code),
  CONSTRAINT FK_civicrm_o8_fund_category_fund_id FOREIGN KEY (`fund_id`) REFERENCES `civicrm_o8_fund`(`id`),
  CONSTRAINT FK_civicrm_o8_fund_category_created_by FOREIGN KEY (`created_by`) REFERENCES `civicrm_contact`(`id`) ON DELETE RESTRICT,
  CONSTRAINT FK_civicrm_o8_fund_category_modified_by FOREIGN KEY (`modified_by`) REFERENCES `civicrm_contact`(`id`) ON DELETE RESTRICT
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_o8_fund_component
-- *
-- * Fund Component
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_fund_component` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique FundComponent ID',
  `code` varchar(255) NOT NULL COMMENT 'Component Code',
  `name` varchar(255) NOT NULL COMMENT 'Component Name',
  `description` text COMMENT 'Optional verbose description of the component.',
  `fund_category_id` int unsigned NOT NULL COMMENT 'FK to civicrm_o8_fund_category',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the component was created',
  `created_by` int unsigned COMMENT 'FK to Created Contact',
  `modified_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the component was modified',
  `modified_by` int unsigned COMMENT 'FK to Modified Contact',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_code`(code),
  INDEX `index_name`(code),
  CONSTRAINT FK_civicrm_o8_fund_component_fund_category_id FOREIGN KEY (`fund_category_id`) REFERENCES `civicrm_o8_fund_category`(`id`),
  CONSTRAINT FK_civicrm_o8_fund_component_created_by FOREIGN KEY (`created_by`) REFERENCES `civicrm_contact`(`id`) ON DELETE RESTRICT,
  CONSTRAINT FK_civicrm_o8_fund_component_modified_by FOREIGN KEY (`modified_by`) REFERENCES `civicrm_contact`(`id`) ON DELETE RESTRICT
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_o8_fund_transaction
-- *
-- * Fund Transaction
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_fund_transaction` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Fund Transaction ID',
  `date` datetime NOT NULL COMMENT 'Transaction Data Time',
  `description` text COMMENT 'Optional verbose description of the transaction.',
  `amount` decimal(20,2) NOT NULL COMMENT 'Amount of the transaction.',
  `file_id` int unsigned NOT NULL COMMENT 'FK to civicrm_file',
  `status_id` int DEFAULT 1,
  `case_id` int unsigned COMMENT 'FK to civicrm_case',
  `contact_id_sub` int unsigned COMMENT 'FK to Contact',
  `contact_id_app` int unsigned COMMENT 'FK to Contact',
  `component_id` int unsigned COMMENT 'FK to civicrm_o8_fund_component',
  `account_id` int unsigned COMMENT 'FK to civicrm_o8_fund_account',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the transaction was created',
  `created_by` int unsigned COMMENT 'FK to Created Contact',
  `modified_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the transaction was modified',
  `modified_by` int unsigned COMMENT 'FK to Modified Contact',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_o8_fund_transaction_file_id FOREIGN KEY (`file_id`) REFERENCES `civicrm_file`(`id`),
  CONSTRAINT FK_civicrm_o8_fund_transaction_case_id FOREIGN KEY (`case_id`) REFERENCES `civicrm_case`(`id`) ON DELETE RESTRICT,
  CONSTRAINT FK_civicrm_o8_fund_transaction_contact_id_sub FOREIGN KEY (`contact_id_sub`) REFERENCES `civicrm_contact`(`id`) ON DELETE RESTRICT,
  CONSTRAINT FK_civicrm_o8_fund_transaction_contact_id_app FOREIGN KEY (`contact_id_app`) REFERENCES `civicrm_contact`(`id`) ON DELETE RESTRICT,
  CONSTRAINT FK_civicrm_o8_fund_transaction_component_id FOREIGN KEY (`component_id`) REFERENCES `civicrm_o8_fund_component`(`id`) ON DELETE RESTRICT,
  CONSTRAINT FK_civicrm_o8_fund_transaction_account_id FOREIGN KEY (`account_id`) REFERENCES `civicrm_o8_fund_account`(`id`) ON DELETE RESTRICT,
  CONSTRAINT FK_civicrm_o8_fund_transaction_created_by FOREIGN KEY (`created_by`) REFERENCES `civicrm_contact`(`id`) ON DELETE RESTRICT,
  CONSTRAINT FK_civicrm_o8_fund_transaction_modified_by FOREIGN KEY (`modified_by`) REFERENCES `civicrm_contact`(`id`) ON DELETE RESTRICT
)
ENGINE=InnoDB;
